name: jet
favicon: null
layout_spectrum: 0.51895
typography_spectrum: 0.19512
title: Jason Erick Taylor
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d3202e'
    - '#000000'
    - '#ffcd32'
    - '#f2f2f4'
    - '#7d7e81'
  brandStrength: 1
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
purpose: []
